version: "3.1"
services:
  redis:
    image: redis:6.2.6
    hostname: redis
    container_name: redis
    command: redis-server --requirepass "secret"
    volumes:
      - redis-data:/data
  visitors:
    build: .
    ports:
      - "65432:65432"
    depends_on:
      - redis
volumes:
  redis-data:
